name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git pull --rebase origin main || true

          git add -A
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "generated"
          git push origin main
