name: Waka Readme

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.MY_PAT }}
          SHOW_TITLE: "true"
          TIME_RANGE: "last_30_days"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "True"
          SHOW_PROFILE_VIEWS: "False"
